program: final_pipeline.py
method: bayes

metric:
  name: val_accuracy
  goal: maximize

parameters:


  # Number of K in KNN algorithm
  K:
    values: [1,2, 3, 4, 5, 6, 7, 8, 9, 10]


  seed:
    value: 42

early_terminate:
  type: hyperband
  min_iter: 5
