# Only the parameters we're searching 
program: src/ml_ops_59/sweep_entry.py
method: bayes

metric:
  name: val_accuracy
  goal: maximize

parameters:
  K:
    values: [1,2,3,4,5,6,7,8,9,10]
  seed:
    value: 42

early_terminate:
  type: hyperband
  min_iter: 5
