_wandb:
    value:
        cli_version: 0.23.1
        e:
            ufk3yd4hmq8tmi2qvluz6tg7pkaiakap:
                args:
                    - --K=8
                    - --seed=42
                codePath: src/ml_ops_59/sweep_entry.py
                codePathLocal: src/ml_ops_59/sweep_entry.py
                email: s214995@dtu.dk
                executable: /Users/victorstege/Documents/GitHub/ML_Ops_59/.venv/bin/python
                git:
                    commit: d1d60b22806cfe8b07aaf9b290568ef9ac177891
                    remote: https://github.com/AlbertFrydensberg/ML_Ops_59.git
                host: MacBook-Air.local
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/victorstege/Documents/GitHub/ML_Ops_59/src/ml_ops_59/sweep_entry.py
                python: CPython 3.12.12
                root: /Users/victorstege/Documents/GitHub/ML_Ops_59
                startedAt: "2026-01-15T13:33:13.620512Z"
                writerId: ufk3yd4hmq8tmi2qvluz6tg7pkaiakap
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 14
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
K:
    value: 8
seed:
    value: 42
